# Generated by Django 5.0 on 2024-01-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBasket', '0002_entrenador_created_entrenador_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='biografia',
            field=models.CharField(default='ValorPredeterminado', max_length=3000),
        ),
        migrations.AddField(
            model_name='equipo',
            name='biografia',
            field=models.CharField(default='ValorPredeterminado', max_length=3000),
        ),
        migrations.AddField(
            model_name='jugador',
            name='biografia',
            field=models.CharField(default='ValorPredeterminado', max_length=3000),
        ),
    ]
