# Generated by Django 5.0 on 2024-01-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBasket', '0004_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'Avatar', 'verbose_name_plural': 'Avatares'},
        ),
        migrations.AlterField(
            model_name='jugador',
            name='biografia',
            field=models.TextField(default='ValorPredeterminado', max_length=3000),
        ),
    ]
