# Generated by Django 5.0 on 2024-01-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBasket', '0005_alter_avatar_options_alter_jugador_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(default='jugadores/basketimagen.jpg', upload_to='jugadores/'),
        ),
    ]
