# Generated by Django 5.0 on 2024-01-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBasket', '0006_jugador_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(default='media/jugadores/basketimagen.jpg', upload_to='media/jugadores/'),
        ),
    ]
