# Generated by Django 5.0 on 2024-01-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBasket', '0007_alter_jugador_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(default='jugadores/basketimagen.jpg', upload_to='jugadores'),
        ),
    ]
