# Generated by Django 5.0 on 2024-01-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBasket', '0008_alter_jugador_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='imagen',
            field=models.ImageField(default='jugadores/basketimagen.jpg', upload_to='jugadores'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(default='jugadores/basketimagen.jpg', upload_to='jugadores'),
        ),
    ]
