# Generated by Django 5.0 on 2024-01-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBasket', '0009_entrenador_imagen_equipo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenador',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='biografia',
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='imagen',
            field=models.ImageField(default='dt/MOU.PNG', upload_to='dt'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='biografia',
            field=models.TextField(default='ValorPredeterminado', max_length=7000),
        ),
    ]
